# Écoute pour l'Extranet (Interface Publique 150.10.0.10)
Listen 150.10.0.10:80
<IfModule ssl_module>
    Listen 150.10.0.10:443
</IfModule>

# Écoute pour l'Intranet (Interface Privée 192.168.10.10)
Listen 192.168.10.10:5501
<IfModule ssl_module>
    Listen 192.168.10.10:5502
</IfModule>
